#!/bin/sh 
#
# If no X server is available, just run upstart, otherwise fall back to the
# traditional X-based desktop session startup.
#

if test -z "$DISPLAY"; then
  export QT_QPA_PLATFORM=ubuntumirclient
  export UNITY_INDICATOR_PROFILE=desktop
  exec init --user
else
  exec /usr/sbin/lightdm-session "$@"
fi
