#!/bin/sh 
#
# If no X server is available, just run upstart, otherwise fall back to the
# traditional X-based desktop session startup.
#

if test -z "$DISPLAY"; then
  exec init --user
else
  exec /usr/sbin/lightdm-session "$@"
fi
