.TH unity8-snap-install "1" "Oct 2016" "unity8-snap-install 1.0.13" "User Commands"

.SH NAME
unity8-snap-install \- install the Unity8 session snap from snap store

.SH DESCRIPTION
usage: unity8\-snap\-install
.PP
Install the Unity8 session snap with the proper arguments passed to the snap command
